[package]
name = "reo_rs"
version = "0.1.0"
authors = ["sirkibsirkib <christopher.esterhuyse@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = "0.2.0"
parking_lot = "0.7.1"
itertools = "0.8.0"
derive-new = "0.5.6"
std-semaphore = "0.1.0"
smallvec = "0.6.9"
crossbeam = "0.7.1"